version: '3'
services:
  debian-desktop:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6080:6080
      - 5900:5900
    environment:
      - DISPLAY=:1
      - RESOLUTION=1920x1080x24
      - USERNAME=hiperesp
      - PASSWORD=senha123456